# finalize sudoers
# removed sudoer files not managed by our playbook
---

- name: finalize | find foreign sudoers
  find:
    paths: "/tmp/sudoers.d"
  register: installed_sudoers

- name: finalize | purge foregin sudoers
  file: path="{{ item.path }}" state=absent
  with_items:
    - "{{ installed_sudoers.files }}"
  when: sudoer_purge and item.path not in sudoer_list

